### ISSUE TITLE
Same commit is repeated while rebase the develop branch issue.

### ISSUE THREAD

**Issue by PraveenKumar2PK** [logeshselvam/forYou#29]
[repeatedCommittedLog.txt](https://github.com/ForYou-Always/forYou/files/2809047/repeatedCommittedLog.txt)

**Comment by vairavan6** [comment]
Steps to avoid the issue while rebasing due to conflicts:

**Never do this:**
    

>  1. git commit / pull - Because this might corrupt our branch with others commits.


**Best Practice:**
    

>  1. after final successful rebase , test for errors & issues.
>  2. Now force push your code.  

         *git push -f*

**Comment by PraveenKumar2PK** [comment]
Thanks anna :)
